// UI文言テーブル(ja/en)。app.js より前に読み込む。手で編集してよい(生成物ではない)。
// fetch не使わず JS 埋め込み = file:// でも動く(README/SPEC の制約)。
// 値は文字列(={k} 補間) か 関数(複数形など)。英語は move/moves の単複を関数で処理する。
window.NIKENZUME_STRINGS = {
  ja: {
    title: 'Tsugai',
    tagline: 'ふたつの部屋、ひとつの操作。',
    chapter: ({ n }) => `第${n}章`,
    modeNormal: '通常', modeAdvanced: '上級',
    // ボタン
    back: '戻る', reset: '最初から', answer: '答え', settings: '設定',
    light: '光ヒント', nextMove: '次の手ヒント',
    hintLight: '光ヒント', hintNext: '次の手', hintAnswer: '答え',
    loginTitle: 'ログインボーナス', loginClaim: '受け取る',
    // 設定
    language: '言語', se: '効果音', haptics: '触覚フィードバック',
    resetProgress: '進捗をリセット', howto: '遊び方', about: 'このアプリについて',
    privacy: 'プライバシーポリシー', contact: 'お問い合わせ', review: 'レビューする',
    removeAds: '広告を消す', restore: '購入を復元',
    secDisplay: '表示', secSound: '音・操作感', secData: 'データ', secInfo: '情報', secPurchase: '購入',
    soon: '準備中',
    resetConfirm: '進捗(クリア・最短の記録)をすべて消去します。よろしいですか?',
    play: '再生', pause: '一時停止', prev: '前へ', next: '次へ', close: 'とじる',
    restart: '初手から', nextPuzzle: '次の問題へ', levels: '一覧へ', retryAgain: 'もう一度',
    // メッセージ
    controlsHint: '矢印キー / スワイプで両方の部屋が動く',
    missNote: 'ゴールは、ふたつ同時でなければ開かない',
    tapHint: '画面をタップ',
    noSolution: 'この局面からは進めません',
    moreSettings: '— 設定は今後ここに —',
    // 動的(数字埋め込み)
    puzzlePar: ({ n }) => `${n}手詰`,
    levelMoves: ({ n }) => `${n}手`,
    moveCount: ({ n }) => `${n}手`,
    clearedMoves: ({ n }) => `${n}手でクリア`,
    fewest: '最短手数です',
    fewestIs: ({ n }) => `最短は${n}手`,
    nextMoveHint: ({ n }) => `次の一手 ・ あと ${n} 手`,
    // 遊び方
    ht1title: '2つの部屋、1つの操作',
    ht1body: '画面には2つの部屋が並んでいます。それぞれの部屋に球が1つずつ。あなたの操作(上下左右)は、両方の球に同時に届きます。',
    ht2title: '同時にゴールへ',
    ht2body: '各部屋にある光の輪がゴールです。2つの球が同じ一手で同時にゴールに入るとクリア。片方だけ先にゴールに入ると失敗です。',
    ht3title: '壁がズレを生む',
    ht3body: '球が壁や外周にぶつかると、その球だけ止まります。もう片方の部屋の球は動く——このズレがパズルの核です。わざと壁にぶつけることで、2つの球の位置関係を調整できます。',
    ht4title: 'ヒントと手戻り',
    ht4body: '詰まったら、画面下の電球でぶつけるべき壁を光らせられます。',
    ht4tip1: 'ぶつけるべき壁が光る',
    ht4tip2: '今の局面から最善の一手を示す',
    ht4tip3: '正解を自動再生する',
    ht4tip4: 'いつでも初形に戻せる',
    // バージョン履歴
    version: 'バージョン履歴', verCurrent: '現在',
    ver100a: '初回リリース', ver100b: '第1章〜第3章（全30問）',
    ver100c: '光ヒント・答え再生', ver100d: 'ライトモード専用デザイン', ver100e: '日本語・英語対応',
    // プライバシーポリシー
    ppDate: '最終更新: 2026年6月',
    ppDataH: '収集するデータ', ppDataP: 'Tsugai はお名前・メールアドレス等の個人情報を収集しません。ゲームの進捗データはすべて端末内に保存されます。',
    ppLocalH: '端末内のデータ', ppLocalP: '以下のデータを端末内（localStorage）に保存します。',
    ppLocal1: 'クリア状況・最短手数の記録', ppLocal2: '表示設定',
    ppLocal3: '効果音・触覚のON/OFF設定', ppLocal4: '言語設定',
    ppLocalNote: 'これらはサーバーには送信されません。設定画面の「進捗をリセット」で全消去できます。',
    ppAdH: '広告', ppAdP: '本アプリでは Google AdMob を利用して広告を表示します。AdMob は広告配信のために広告ID・デバイス情報を収集することがあります。詳細は Google のプライバシーポリシーをご確認ください。',
    ppAdLink: 'Google プライバシーポリシー ↗',
    ppAnalyticsH: 'アナリティクス', ppAnalyticsP: 'アプリの改善のため、Firebase Analytics を利用して利用状況を匿名で収集します。個人を特定する情報は含まれません。',
    ppContactH: 'お問い合わせ', ppContactP: 'ご質問がある場合は、設定画面の「お問い合わせ」からご連絡ください。',
    // お問い合わせ
    contactDesc: 'バグの報告やご意見・ご要望はメールでお送りください。', contactSend: 'メールを送る',
    ht1cap: 'スワイプひとつで、両方の球が同時に動く',
    ht2ok: 'クリア', ht2ng: '失敗',
    ht3before: '操作前', ht3after: '→ を入力',
    ht3same: '同じ位置', ht3gap: '壁で止まる = ズレ発生',
    ht5title: '最短を目指す',
    ht5body: '各問題には最短手数があります。最短でクリアすると金の印が付きます。まずはクリアを目指し、次に最短に挑戦してみてください。',
    // デイリーチャレンジ
    dailyTitle: 'デイリー',
    dailyNew: '挑戦する',
    dailyCleared: 'クリア済み',
    dailyBest: 'ベスト達成',
    dailyStreak: ({ n }) => `🔥 ${n}日連続`,
    dailyReward: 'クリア報酬',
    dailyStreakBonus: ({ n }) => `${n}日連続ボーナス`,
    dailyShare: 'シェア',
    dailyShareText: ({ day, moves, best, streak }) =>
      `Tsugai デイリー #${day}\n${moves}手でクリア${best ? ' ⭐' : ''}${streak > 0 ? `\n🔥 ${streak}日連続` : ''}`,
    copied: 'コピーしました',
    // 統計・実績
    stats: '統計・実績',
    statCleared: 'クリア', statBest: 'ベスト',
    statDaily: 'デイリー',
    statDaysPlayed: 'クリア日数', statCurrentStreak: '現在の連続', statMaxStreak: '最長連続',
    statAchievements: '実績',
    ach_clear1: '初クリア', ach_clear10: '10問クリア', ach_clear50: '50問クリア', ach_clear100: '100問クリア',
    ach_best1: '初ベスト', ach_best10: 'ベスト10達成', ach_best50: 'ベスト50達成',
    ach_daily1: 'デイリー初クリア', ach_streak7: '7日連続', ach_streak14: '14日連続', ach_streak30: '30日連続',
  },
  en: {
    title: 'Tsugai',
    tagline: 'Two rooms, one move.',
    chapter: ({ n }) => `Chapter ${n}`,
    modeNormal: 'Normal', modeAdvanced: 'Advanced',
    back: 'Back', reset: 'Restart', answer: 'Answer', settings: 'Settings',
    light: 'Light hint', nextMove: 'Next move',
    hintLight: 'Light', hintNext: 'Next move', hintAnswer: 'Answer',
    loginTitle: 'Login Bonus', loginClaim: 'Claim',
    // settings
    language: 'Language', se: 'Sound', haptics: 'Haptics',
    resetProgress: 'Reset progress', howto: 'How to play', about: 'About',
    privacy: 'Privacy policy', contact: 'Contact', review: 'Rate',
    removeAds: 'Remove ads', restore: 'Restore purchases',
    secDisplay: 'Display', secSound: 'Sound & feel', secData: 'Data', secInfo: 'Info', secPurchase: 'Purchases',
    soon: 'Coming soon',
    resetConfirm: 'This will erase all progress (clear & best records). Continue?',
    play: 'Play', pause: 'Pause', prev: 'Prev', next: 'Next', close: 'Close',
    restart: 'Retry', nextPuzzle: 'Next puzzle', levels: 'Levels', retryAgain: 'Try again',
    controlsHint: 'Arrow keys or swipe move both rooms',
    missNote: 'The goal opens only when both arrive together.',
    tapHint: 'Tap to continue',
    noSolution: 'No solution from here',
    moreSettings: '— more settings soon —',
    puzzlePar: ({ n }) => `Solve in ${n}`,
    levelMoves: ({ n }) => `${n}`,
    moveCount: ({ n }) => `${n} ${n === 1 ? 'move' : 'moves'}`,
    clearedMoves: ({ n }) => `Cleared in ${n} ${n === 1 ? 'move' : 'moves'}`,
    fewest: 'Fewest moves!',
    fewestIs: ({ n }) => `Fewest is ${n} ${n === 1 ? 'move' : 'moves'}`,
    nextMoveHint: ({ n }) => `Next · ${n} to go`,
    // How to play
    ht1title: 'Two rooms, one move',
    ht1body: 'Two rooms sit side by side, each with a ball inside. Every move you make—up, down, left, or right—reaches both balls at once.',
    ht2title: 'Reach the goal together',
    ht2body: 'The glowing ring in each room is the goal. Clear the puzzle by landing both balls on their goals in a single move. If only one ball enters its goal, that\'s a miss.',
    ht3title: 'Walls create the gap',
    ht3body: 'When a ball hits a wall or the edge, it stays put—while the other ball keeps moving. This gap is the heart of every puzzle. Deliberately bumping into walls lets you adjust the positions of the two balls.',
    ht4title: 'Hints & restart',
    ht4body: 'Stuck? Tap the light bulb at the bottom to highlight the wall to bump.',
    ht4tip1: 'Highlights the walls to bump',
    ht4tip2: 'Shows the best next move',
    ht4tip3: 'Auto-plays the solution',
    ht4tip4: 'Return to the starting position',
    // Version history
    version: 'Version history', verCurrent: 'Current',
    ver100a: 'Initial release', ver100b: 'Chapters 1–3 (30 puzzles)',
    ver100c: 'Light hint & answer playback', ver100d: 'Light-only visual design', ver100e: 'Japanese & English',
    // Privacy policy
    ppDate: 'Last updated: June 2026',
    ppDataH: 'Data we collect', ppDataP: 'Tsugai does not collect personal information such as your name or email address. Game progress is stored entirely on your device.',
    ppLocalH: 'On-device data', ppLocalP: 'The following data is saved locally (localStorage):',
    ppLocal1: 'Clear status & best move counts', ppLocal2: 'Display preference',
    ppLocal3: 'Sound & haptics on/off', ppLocal4: 'Language setting',
    ppLocalNote: 'None of this is sent to a server. Use "Reset progress" in Settings to erase it all.',
    ppAdH: 'Advertising', ppAdP: 'This app displays ads via Google AdMob. AdMob may collect your advertising ID and device information to serve ads. See Google\'s Privacy Policy for details.',
    ppAdLink: 'Google Privacy Policy ↗',
    ppAnalyticsH: 'Analytics', ppAnalyticsP: 'To improve the app, we collect anonymous usage data via Firebase Analytics. No personally identifiable information is included.',
    ppContactH: 'Contact', ppContactP: 'If you have questions, please reach out via "Contact" in the Settings screen.',
    // Contact
    contactDesc: 'To report bugs or share feedback, please send us an email.', contactSend: 'Send email',
    ht1cap: 'One swipe moves both balls at once',
    ht2ok: 'Clear', ht2ng: 'Miss',
    ht3before: 'Before', ht3after: 'Swipe →',
    ht3same: 'Same position', ht3gap: 'Blocked by wall = gap created',
    ht5title: 'Aim for the fewest moves',
    ht5body: 'Every puzzle has an optimal move count. Clearing in the fewest moves earns a gold mark. Start by clearing, then challenge yourself to find the shortest path.',
    // Daily challenge
    dailyTitle: 'Daily',
    dailyNew: 'Play',
    dailyCleared: 'Cleared',
    dailyBest: 'Best!',
    dailyStreak: ({ n }) => `🔥 ${n} day streak`,
    dailyReward: 'Reward',
    dailyStreakBonus: ({ n }) => `${n}-day streak bonus`,
    dailyShare: 'Share',
    dailyShareText: ({ day, moves, best, streak }) =>
      `Tsugai Daily #${day}\nCleared in ${moves} ${moves === 1 ? 'move' : 'moves'}${best ? ' ⭐' : ''}${streak > 0 ? `\n🔥 ${streak} day streak` : ''}`,
    copied: 'Copied',
    // Stats & achievements
    stats: 'Stats',
    statCleared: 'Cleared', statBest: 'Best',
    statDaily: 'Daily',
    statDaysPlayed: 'Days cleared', statCurrentStreak: 'Current streak', statMaxStreak: 'Best streak',
    statAchievements: 'Achievements',
    ach_clear1: 'First clear', ach_clear10: '10 puzzles cleared', ach_clear50: '50 puzzles cleared', ach_clear100: '100 puzzles cleared',
    ach_best1: 'First best', ach_best10: '10 bests', ach_best50: '50 bests',
    ach_daily1: 'First daily clear', ach_streak7: '7-day streak', ach_streak14: '14-day streak', ach_streak30: '30-day streak',
  },
};
